on: push
name: phpcs
jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: PHP_CodeSniffer
        uses: chekalsky/phpcs-action@option-installed-paths
        with:
          installed_paths: /github/workspace/vendor/phpcompatibility/phpcompatibility-wp
